name: Create Folder

on:
  push:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - name: Check FIles
      - uses: actions/checkout@v4.3.1
      
      - name: Create a New Folder
        run: |
             mkdiir manish
             echo "Hello" > /manish/test.txt
             touch /manish/manish.txt
